### ISSUE TITLE
Deep Reinforcement Learning-Based Modulation and Coding Scheme Selection in Cognitive Heterogeneous Networks

### ISSUE THREAD

**Issue by Msixram** [ML4Comm-Netw/Paper-with-Code-of-Wireless-communication-Based-on-DL#33]
L. Zhang, J. Tan, Y. -C. Liang, G. Feng and D. Niyato, "Deep Reinforcement Learning-Based Modulation and Coding Scheme Selection in Cognitive Heterogeneous Networks," in IEEE Transactions on Wireless Communications, vol. 18, no. 6, pp. 3281-3294, June 2019, doi: 10.1109/TWC.2019.2912754.

URL：https://ieeexplore.ieee.org/document/8703432

**Comment by liyiq5** [comment]
邮件已经收到，谢谢，祝好~！

**Comment by Charlie258** [comment]
你好，你的邮件已经收到，谢谢。
